// <auto-generated />
using CasaDoCodigo.Areas.Catalogo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasaDoCodigo.Areas.Carrinho.Data.Migrations
{
    [DbContext(typeof(CarrinhoDbContext))]
    [Migration("20200308025631_Carrinho")]
    partial class Carrinho
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CasaDoCodigo.Areas.Carrinho.Models.Carrinho", b =>
                {
                    b.Property<string>("ClienteId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ClienteId");

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("CasaDoCodigo.Areas.Carrinho.Models.ItemCarrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrinhoClienteId")
                        .IsRequired();

                    b.Property<decimal>("PrecoUnitario");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired();

                    b.Property<string>("ProdutoNome")
                        .IsRequired();

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoClienteId");

                    b.ToTable("ItemCarrinho");
                });

            modelBuilder.Entity("CasaDoCodigo.Areas.Carrinho.Models.ItemCarrinho", b =>
                {
                    b.HasOne("CasaDoCodigo.Areas.Carrinho.Models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
